### ISSUE TITLE
SSL Certificate / Load balancer

### ISSUE THREAD

**Issue by MartinPaulEve** [DeYoungTech/terraform-provider-awslightsail#25] opened 2022-06-01 10:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At present, we have the ability to create Lightsail certificates:

```
resource "awslightsail_certificate" "cert" {
  name                      = "certificate"
  domain_name               = var.domain_name
  subject_alternative_names = ["www.${var.domain_name}"]
  provider                  = awslightsail.domain
}
```

However, I can see no way, at the moment, to associate that certificate with the load balancer. I can see that the container deployment allows the user to specify a certificate, but wondered whether this functionality exists or is planned?

### New or Affected Resource(s)

* awslightsail_certificate
* awslightsail_lb

**Comment by brittandeyoung** [comment] 2022-06-08 15:01
@MartinPaulEve The certificates that are associated with load balancers is a separate resource than the current `awslightsail_certificate` https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#Lightsail.CreateLoadBalancerTlsCertificate

If you are looking to contribute this resource, please feel free to open a PR. If not, I will see when I am able to get around to writing this one.

**Comment by brittandeyoung** [comment] 2022-06-08 15:04
example config would look like:
```terraform
resource "awslightsail_lb_certificate" "cert" {
  name = "CertificateName"
  alternative_names = [
    "test1.example.com"
  ]
  domain_name = "test.example.com"
  load_balancer_name = "MYLoadBalancer"
}
```

**Comment by MartinPaulEve** [comment] 2022-06-08 15:15
Hi @brittandeyoung - thanks for the reply!

I am afraid that I don't know any Go -- just a Terraform user and found your great provider, here -- so not sure I am qualified to contribute this myself.

However, if this were in place, I'd love to write up my infrastructure and spread the word about this provider.

It's somewhat strange that the official provider doesn't offer even what you've achieved here, already!

**Comment by brittandeyoung** [comment] 2022-06-08 15:20
@MartinPaulEve I have been attempting to add more lightsail resources to the official AWS provider and have a few pull requests open. The issue is the limited number of reviewers, and they review what gets the most upvotes. Unfortunately lightsail does not receive many upvotes. This is what led me to start this separate provider. 

I have been contributing some resources to the main provider recently, but i will see if i can find some time to keep adding to this provider as well.

**Comment by MartinPaulEve** [comment] 2022-06-08 15:22
Thank you! Just to say that I appreciate it / your work!

**Comment by brittandeyoung** [comment] 2022-10-26 15:03
@MartinPaulEve For awareness, I have been contributing back to the main AWS provider. I have added support for lb certificates and will be released soon: https://github.com/hashicorp/terraform-provider-aws/pull/27462

**Comment by MartinPaulEve** [comment] 2022-10-27 15:43
Thanks so much for this! That's great to see.

I am afraid I am quite seriously unwell in hospital right now, so am unsure when I will be able to play with this, but I'm looking forward to it.

Great to see it's in the main provider, too.

**Closed as completed** 2023-02-07 13:29 UTC
Labels: enhancement
